<a href="https://colab.research.google.com/github/vbloise3/deepLearning/blob/master/testNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

x = np.array([[[5, 78, 2, 34, 0, 8],
 [6, 79, 3, 35, 1, 7],
 [7, 80, 4, 36, 2, 6]],
 [[5, 78, 2, 34, 0, 5],
 [6, 79, 3, 35, 1, 4],
 [7, 80, 4, 36, 2, 3]],
 [[5, 78, 2, 34, 0, 2],
 [6, 79, 3, 35, 1, 1],
 [7, 80, 4, 36, 2, 0]]])
print(f"x: {x}")
print(f"x dimension: {x.ndim}")
print(f"x shape: {x.shape}")
print(f"x type: {x.dtype}")

users = [
    { "id": 0, "name": "Hero" },
    { "id": 1, "name": "Dunn" },
    { "id": 2, "name": "Sue" },
    { "id": 3, "name": "Chi" },
    { "id": 4, "name": "Thor" },
    { "id": 5, "name": "Clive" },
    { "id": 6, "name": "Hicks" },
    { "id": 7, "name": "Devin" },
    { "id": 8, "name": "Kate" },
    { "id": 9, "name": "Klein" }
]
friendship_pairs = [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3), (3, 4), (4, 5), 
                    (5, 6), (5, 7), (6, 8), (7, 8), (8, 9)]


x: [[[ 5 78  2 34  0  8]
  [ 6 79  3 35  1  7]
  [ 7 80  4 36  2  6]]

 [[ 5 78  2 34  0  5]
  [ 6 79  3 35  1  4]
  [ 7 80  4 36  2  3]]

 [[ 5 78  2 34  0  2]
  [ 6 79  3 35  1  1]
  [ 7 80  4 36  2  0]]]
x dimension: 3
x shape: (3, 3, 6)
x type: int64
