<a href="https://colab.research.google.com/github/vbloise3/deepLearning/blob/master/testNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from collections import Counter

x = np.array([[[5, 78, 2, 34, 0, 8],
 [6, 79, 3, 35, 1, 7],
 [7, 80, 4, 36, 2, 6]],
 [[5, 78, 2, 34, 0, 5],
 [6, 79, 3, 35, 1, 4],
 [7, 80, 4, 36, 2, 3]],
 [[5, 78, 2, 34, 0, 2],
 [6, 79, 3, 35, 1, 1],
 [7, 80, 4, 36, 2, 0]]])
print(f"x: {x}")
print(f"x dimension: {x.ndim}")
print(f"x shape: {x.shape}")
print(f"x type: {x.dtype}")


# First example from Data Science From Scratch book
users = [
    { "id": 0, "name": "Hero" },
    { "id": 1, "name": "Dunn" },
    { "id": 2, "name": "Sue" },
    { "id": 3, "name": "Chi" },
    { "id": 4, "name": "Thor" },
    { "id": 5, "name": "Clive" },
    { "id": 6, "name": "Hicks" },
    { "id": 7, "name": "Devin" },
    { "id": 8, "name": "Kate" },
    { "id": 9, "name": "Klein" }
]
friendship_pairs = [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3), (3, 4), (4, 5), 
                    (5, 6), (5, 7), (6, 8), (7, 8), (8, 9)]
# Initialize the dict with an empty list for each user id
friendships = {user["id"]: [] for user in users}
print(f"\nfriendships after empty init: {friendships}\n")

# Add loop over the friendship pairs to populate it
for i, j in friendship_pairs:
  friendships[i].append(j) # Add j as a friend of user i
  friendships[j].append(i) # Add i as a friend of user j
  
print(f"\nfriendships after data load in for i, j loop: {friendships}\n")
  
def number_of_friends(user):
  """How many friends does user have?"""
  user_id = user["id"]
  friend_ids = friendships[user_id]
  return len(friend_ids)

def friends_of_friends(user):
  user_id = user["id"]
  return Counter(foaf_id for friend_id in friendships[user_id] # for each of my friends,
                 for foaf_id in friendships[friend_id] # find their friends
                     if foaf_id != user_id # who aren't me
                     and foaf_id not in friendships[user_id] # and aren't my friends
                )


total_connections = sum(number_of_friends(user) for user in users)

print(f"friends of 1: {friendships[1]}\n")

print(f"number of friends of 4: {number_of_friends(users[4])}\n")

print(f"number of connections: {total_connections}")
num_users = len(users)
# length of the users list
avg_connections = total_connections / num_users 
print(f"average connections: {avg_connections}\n")

# sort the friends by number of connections
# Create a list (user_id, number_of_friends)
num_friends_by_id = [(user["id"], number_of_friends(user)) for user in users]
print(f"number of friends by id: {num_friends_by_id}\n")
print(f"sorted by connections: {num_friends_by_id.sort(key=lambda id_and_friends: id_and_friends[1], reverse=True)}\n")
# largest to smallest

print(f"friends of friends of user 3: {friends_of_friends(users[3])}\n")



x: [[[ 5 78  2 34  0  8]
  [ 6 79  3 35  1  7]
  [ 7 80  4 36  2  6]]

 [[ 5 78  2 34  0  5]
  [ 6 79  3 35  1  4]
  [ 7 80  4 36  2  3]]

 [[ 5 78  2 34  0  2]
  [ 6 79  3 35  1  1]
  [ 7 80  4 36  2  0]]]
x dimension: 3
x shape: (3, 3, 6)
x type: int64

friendships after empty init: {0: [], 1: [], 2: [], 3: [], 4: [], 5: [], 6: [], 7: [], 8: [], 9: []}


friendships after data load in for i, j loop: {0: [1, 2], 1: [0, 2, 3], 2: [0, 1, 3], 3: [1, 2, 4], 4: [3, 5], 5: [4, 6, 7], 6: [5, 8], 7: [5, 8], 8: [6, 7, 9], 9: [8]}

friends of 1: [0, 2, 3]

number of friends of 4: 2

number of connections: 24
average connections: 2.4

number of friends by id: [(0, 2), (1, 3), (2, 3), (3, 3), (4, 2), (5, 3), (6, 2), (7, 2), (8, 3), (9, 1)]

sorted by connections: None

friends of friends of user 3: Counter({0: 2, 5: 1})



In [1]:
from google.colab import drive
drive.mount('/content/gdrive')


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive
