<a href="https://colab.research.google.com/github/vbloise3/deepLearning/blob/master/testNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from collections import Counter
from collections import defaultdict

x = np.array([[[5, 78, 2, 34, 0, 8],
 [6, 79, 3, 35, 1, 7],
 [7, 80, 4, 36, 2, 6]],
 [[5, 78, 2, 34, 0, 5],
 [6, 79, 3, 35, 1, 4],
 [7, 80, 4, 36, 2, 3]],
 [[5, 78, 2, 34, 0, 2],
 [6, 79, 3, 35, 1, 1],
 [7, 80, 4, 36, 2, 0]]])
print(f"x: {x}")
print(f"x dimension: {x.ndim}")
print(f"x shape: {x.shape}")
print(f"x type: {x.dtype}")


# First example from Data Science From Scratch book
users = [
    { "id": 0, "name": "Hero" },
    { "id": 1, "name": "Dunn" },
    { "id": 2, "name": "Sue" },
    { "id": 3, "name": "Chi" },
    { "id": 4, "name": "Thor" },
    { "id": 5, "name": "Clive" },
    { "id": 6, "name": "Hicks" },
    { "id": 7, "name": "Devin" },
    { "id": 8, "name": "Kate" },
    { "id": 9, "name": "Klein" }
]
friendship_pairs = [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3), (3, 4), (4, 5), 
                    (5, 6), (5, 7), (6, 8), (7, 8), (8, 9)]
# Initialize the dict with an empty list for each user id
friendships = {user["id"]: [] for user in users}
print(f"\nfriendships after empty init: {friendships}\n")

# Add loop over the friendship pairs to populate it
for i, j in friendship_pairs:
  friendships[i].append(j) # Add j as a friend of user i
  friendships[j].append(i) # Add i as a friend of user j
  
print(f"\nfriendships after data load in for i, j loop: {friendships}\n")
  
def number_of_friends(user):
  """How many friends does user have?"""
  user_id = user["id"]
  friend_ids = friendships[user_id]
  return len(friend_ids)

def friends_of_friends(user):
  user_id = user["id"]
  return Counter(foaf_id for friend_id in friendships[user_id] # for each of my friends,
                 for foaf_id in friendships[friend_id] # find their friends
                     if foaf_id != user_id # who aren't me
                     and foaf_id not in friendships[user_id] # and aren't my friends
                )


total_connections = sum(number_of_friends(user) for user in users)

print(f"friends of 1: {friendships[1]}\n")

print(f"number of friends of 4: {number_of_friends(users[4])}\n")

print(f"number of connections: {total_connections}")
num_users = len(users)
# length of the users list
avg_connections = total_connections / num_users 
print(f"average connections: {avg_connections}\n")

# sort the friends by number of connections
# Create a list (user_id, number_of_friends)
num_friends_by_id = [(user["id"], number_of_friends(user)) for user in users]
print(f"number of friends by id: {num_friends_by_id}\n")
print(f"sorted by connections: {num_friends_by_id.sort(key=lambda id_and_friends: id_and_friends[1], reverse=True)}\n")
# largest to smallest

print(f"friends of friends of user 3: {friends_of_friends(users[3])}\n")

interests = [
    (0, "Hadoop"), (0, "Big Data"), (0, "HBase"), (0, "Java"), (0, "Spark"), (0, "Storm"),
    (0, "Cassandra"), (1, "NoSQL"), (1, "MongoDB"), (1, "Cassandra"), (1, "HBase"),
    (1, "Postgres"), (2, "Python"), (2, "scikit-learn"), (2, "scipy"), (2, "numpy"),
    (2, "statsmodels"), (2, "pandas"), (3, "R"), (3, "Python"), (3, "statistics"),
    (3, "regression"), (3, "probability"), (4, "machine learning"), (4, "decision trees"),
    (4, "libsvm"), (5,"Python"), (5, "R"), (5, "Java"), (5, "C++"), (5, "Haskell"), (5, "programming languages"),
    (6, "statistics"), (6, "probability"), (6, "mathematics"), (6, "theory"), (7, "machine learning"),
    (7, "scikit-learn"), (7, "Mahout"), (7, "neural networks"), (8, "neural networks"),
    (8, "deep learning"), (8, "Big Data"), (8, "artificial intelligence"), (9, "Hadoop"),
    (9, "Java"), (9, "MapReduce"), (9, "Big Data")
]

def data_scientists_who_like(target_interest):
  """Find the ids of all users who like the target interest"""
  return [user_id for user_id, user_interest in interests
         if user_interest == target_interest]

# Keys are interests, values are lists of user_ids with that interest
user_ids_by_interest = defaultdict(list)

for user_id, interest in interests:
  user_ids_by_interest[interest].append(user_id)
  
# Keys are user_ids, values are lists of interests for that user_id
interests_by_user_id = defaultdict(list)

for user_id, interest in interests:
  interests_by_user_id[user_id].append(interest)
  
def most_common_interests_with(user):
  return Counter(
  interested_user_id for interest in interests_by_user_id[user["id"]]
  for interested_user_id in user_ids_by_interest[interest]
  if interested_user_id != user["id"]
  )

print(f"most common interests with Chi: {most_common_interests_with(users[3])}\n")

x: [[[ 5 78  2 34  0  8]
  [ 6 79  3 35  1  7]
  [ 7 80  4 36  2  6]]

 [[ 5 78  2 34  0  5]
  [ 6 79  3 35  1  4]
  [ 7 80  4 36  2  3]]

 [[ 5 78  2 34  0  2]
  [ 6 79  3 35  1  1]
  [ 7 80  4 36  2  0]]]
x dimension: 3
x shape: (3, 3, 6)
x type: int64

friendships after empty init: {0: [], 1: [], 2: [], 3: [], 4: [], 5: [], 6: [], 7: [], 8: [], 9: []}


friendships after data load in for i, j loop: {0: [1, 2], 1: [0, 2, 3], 2: [0, 1, 3], 3: [1, 2, 4], 4: [3, 5], 5: [4, 6, 7], 6: [5, 8], 7: [5, 8], 8: [6, 7, 9], 9: [8]}

friends of 1: [0, 2, 3]

number of friends of 4: 2

number of connections: 24
average connections: 2.4

number of friends by id: [(0, 2), (1, 3), (2, 3), (3, 3), (4, 2), (5, 3), (6, 2), (7, 2), (8, 3), (9, 1)]

sorted by connections: None

friends of friends of user 3: Counter({0: 2, 5: 1})

most common interests with Chi: Counter({5: 2, 6: 2, 2: 1})

